In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import math

In [15]:
torch.manual_seed(1337)
X = torch.rand(12).reshape((3, -1))
Y = torch.tensor([[3, 4, 5, 6], [7, 8, 9, 10], [11, 12, 13, 14]])
# 18, 34, 50 = 102

torch.manual_seed(1337)
Z = torch.rand(12).reshape((3, -1))
Z[:2, :] = 35
v = torch.cat((X, Y), dim=0)
w = torch.cat((X, Y), dim=1)
X!=Z, torch.tril(Z), Y.sum(dim=1)

(tensor([[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [False, False, False, False]]),
 tensor([[35.0000,  0.0000,  0.0000,  0.0000],
         [35.0000, 35.0000,  0.0000,  0.0000],
         [ 0.1761,  0.2595,  0.7086,  0.0000]]),
 tensor([18, 34, 50]))

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

## Rules of matrix multiplication
<u>**Inner dimensions must match**</u>  
- (3, 2) @ (2, 9) - will work because 2==2  
<u>**Commutative rule of multiplication does not hold!**</u>  
- AB != BA  
<u>**Associative property of multiplication**</u>  
- (AB)C = B(AC)  
<u>**Distributive property of multiplication**</u>  
- A(B + C) = AB + AC  
<u>**Dimension property**</u>  
- The product of `m x n` and `n x k` is a `m x k` matrix  
(3, 2) @ (2,3) = (3,3)

In [28]:
X = torch.rand(12, dtype=torch.float32).reshape((4, -1))
Y = torch.tensor([[3, 4, 5, 6], [7, 8, 9, 10], [11, 12, 13, 14]], dtype=torch.float32)
idx = id(X)
X[:] = Y @ X



RuntimeError: The expanded size of the tensor (4) must match the existing size (3) at non-singleton dimension 0.  Target sizes: [4, 3].  Tensor sizes: [3, 3]